---
abstract: 'Tapper - Backend functions for CLI and Web'
author:
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-Cmd
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Kwalify: 0
  MooseX::Declare: 0
  Tapper::Model: 3.000002
  YAML::Syck: 1.17
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Tapper-Cmd
  repository: git://github.com/amd/Tapper-Cmd.git
version: 3.000004
